seed: 42
input_path: ../datasets/omni_ner_dataset_v1/omni_ner_dataset.json
use_wandb: false
save_model: true

data:
  test_fraction: 0.01
  content_multiplier: 4
  n_descriptions_per_entity: 4
  output_dir: ../datasets/cache/r_arc

model:
  backbone_path: microsoft/deberta-v3-large
  max_length: 1200
  num_proc: 4
  skip_dropout: false
  use_gradient_checkpointing: false
  arcface:
    margin: 0.3
    scale: 25
    n_groups: ??

train_params:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4 # 4
  num_train_epochs: 2
  gradient_accumulation_steps: 4
  warmup_pct: 0.25
  eval_frequency: 100
  patience: 1000

optimizer:
  name: AdamW8bit
  head_lr: 4e-6
  lr: 4e-5
  weight_decay: 1e-3
  max_grad_norm: 0.5

outputs:
  model_dir: ../models/r_arc_omni_ner_large

wandb:
  project: omni-ner
  run_name: exp002-large
  tags:
    - deberta